# Generated by Django 4.0.2 on 2022-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_zherler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atu', models.TextField(blank=True)),
                ('avtor', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tagam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atu', models.CharField(max_length=250)),
                ('malimet', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atu', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hrana',
        ),
        migrations.DeleteModel(
            name='Turleri',
        ),
        migrations.DeleteModel(
            name='Zherler',
        ),
    ]
