# Generated by Django 4.0.2 on 2022-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_makal_tagam_urum_delete_hrana_delete_turleri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ulttyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malimet', models.TextField(blank=True)),
            ],
        ),
    ]
