# Generated by Django 4.0.2 on 2022-03-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_ulttyk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagam',
            new_name='Salt',
        ),
        migrations.DeleteModel(
            name='ulttyk',
        ),
    ]
